<?php

namespace Container3TymSNj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_59ut2QWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.59ut2QW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.59ut2QW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'realisateur' => ['privates', '.errored..service_locator.59ut2QW.App\\Entity\\Realisateur', NULL, 'Cannot autowire service ".service_locator.59ut2QW": it needs an instance of "App\\Entity\\Realisateur" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'realisateur' => 'App\\Entity\\Realisateur',
            'entityManager' => '?',
        ]);
    }
}
