<?php

namespace ContainerE2bqdsJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActeurControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cD87mKW.App\Controller\ActeurController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cD87mKW.App\\Controller\\ActeurController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'acteurRepository' => ['privates', 'App\\Repository\\ActeurRepository', 'getActeurRepositoryService', true],
        ], [
            'acteurRepository' => 'App\\Repository\\ActeurRepository',
        ]))->withContext('App\\Controller\\ActeurController::index()', $container);
    }
}
