<?php

namespace ContainerE2bqdsJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActeurControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lHKLoGi.App\Controller\ActeurController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lHKLoGi.App\\Controller\\ActeurController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'acteur' => ['privates', '.errored..service_locator.lHKLoGi.App\\Entity\\Acteur', NULL, 'Cannot autowire service ".service_locator.lHKLoGi": it needs an instance of "App\\Entity\\Acteur" but this type has been excluded in "config/services.yaml".'],
        ], [
            'acteur' => 'App\\Entity\\Acteur',
        ]))->withContext('App\\Controller\\ActeurController::show()', $container);
    }
}
