<?php

namespace ContainerE2bqdsJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilmControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FSMk43a.App\Controller\FilmController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FSMk43a.App\\Controller\\FilmController::delete()'] = ($container->privates['.service_locator.FSMk43a'] ?? $container->load('get_ServiceLocator_FSMk43aService'))->withContext('App\\Controller\\FilmController::delete()', $container);
    }
}
