<?php

namespace ContainerE2bqdsJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRealisateurControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.59ut2QW.App\Controller\RealisateurController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.59ut2QW.App\\Controller\\RealisateurController::delete()'] = ($container->privates['.service_locator.59ut2QW'] ?? $container->load('get_ServiceLocator_59ut2QWService'))->withContext('App\\Controller\\RealisateurController::delete()', $container);
    }
}
