<?php

namespace ContainerE2bqdsJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRealisateurControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.59ut2QW.App\Controller\RealisateurController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.59ut2QW'] ?? $container->load('get_ServiceLocator_59ut2QWService'));

        if (isset($container->privates['.service_locator.59ut2QW.App\\Controller\\RealisateurController::edit()'])) {
            return $container->privates['.service_locator.59ut2QW.App\\Controller\\RealisateurController::edit()'];
        }

        return $container->privates['.service_locator.59ut2QW.App\\Controller\\RealisateurController::edit()'] = $a->withContext('App\\Controller\\RealisateurController::edit()', $container);
    }
}
