<?php

namespace ContainerE2bqdsJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRealisateurControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y52RLI5.App\Controller\RealisateurController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y52RLI5.App\\Controller\\RealisateurController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'realisateur' => ['privates', '.errored..service_locator.Y52RLI5.App\\Entity\\Realisateur', NULL, 'Cannot autowire service ".service_locator.Y52RLI5": it needs an instance of "App\\Entity\\Realisateur" but this type has been excluded in "config/services.yaml".'],
        ], [
            'realisateur' => 'App\\Entity\\Realisateur',
        ]))->withContext('App\\Controller\\RealisateurController::show()', $container);
    }
}
