<?php

namespace ContainerE2bqdsJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRealisateurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.59ut2QW.App\Entity\Realisateur' shared service.
     *
     * @return \App\Entity\Realisateur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.59ut2QW": it needs an instance of "App\\Entity\\Realisateur" but this type has been excluded in "config/services.yaml".');
    }
}
