<?php

namespace ContainerYk60Vmh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FSMk43aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FSMk43a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FSMk43a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'film' => ['privates', '.errored..service_locator.FSMk43a.App\\Entity\\Film', NULL, 'Cannot autowire service ".service_locator.FSMk43a": it needs an instance of "App\\Entity\\Film" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'film' => 'App\\Entity\\Film',
            'entityManager' => '?',
        ]);
    }
}
