<?php

namespace ContainerYk60Vmh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActeurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YcdKq5l.App\Entity\Acteur' shared service.
     *
     * @return \App\Entity\Acteur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.YcdKq5l": it needs an instance of "App\\Entity\\Acteur" but this type has been excluded in "config/services.yaml".');
    }
}
