<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE2bqdsJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE2bqdsJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE2bqdsJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE2bqdsJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE2bqdsJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'E2bqdsJ',
    'container.build_id' => '6b73511f',
    'container.build_time' => 1730909737,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE2bqdsJ');
