<?php

namespace Container2x75mkq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRealisateurControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cyrhMfC.App\Controller\RealisateurController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cyrhMfC.App\\Controller\\RealisateurController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'realisateurRepository' => ['privates', 'App\\Repository\\RealisateurRepository', 'getRealisateurRepositoryService', true],
        ], [
            'realisateurRepository' => 'App\\Repository\\RealisateurRepository',
        ]))->withContext('App\\Controller\\RealisateurController::index()', $container);
    }
}
