<?php

namespace Container2x75mkq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilisateurControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LVPv12D.App\Controller\UtilisateurController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.LVPv12D'] ?? $container->load('get_ServiceLocator_LVPv12DService'));

        if (isset($container->privates['.service_locator.LVPv12D.App\\Controller\\UtilisateurController::edit()'])) {
            return $container->privates['.service_locator.LVPv12D.App\\Controller\\UtilisateurController::edit()'];
        }

        return $container->privates['.service_locator.LVPv12D.App\\Controller\\UtilisateurController::edit()'] = $a->withContext('App\\Controller\\UtilisateurController::edit()', $container);
    }
}
